// Dynaserver.cpp
#define    WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdlib.h>

#include "pansi.h"    // header file generated by MIDL compiler
#include "panserver.h"
#include "panserver2.h"


int main(int atgc, char *argv[])
{
	if (FrontEndSetup() < 0)
	{
		DebugPrintln("FrontEnd Setup Failure.");
		exit(-1);
	}
	DebugPrintln("FrontEnd Setup OK.");

	int i;
	DWORD id;
	for (i = 0; i < System.nstation; i++)
	{
		int station = i;
		CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)FrontEndRoutine, (LPVOID)station, 0, &id);
	}
	CreateThread (NULL, 0, (LPTHREAD_START_ROUTINE)RPCSetup, 0, 0, &id);
	DebugPrintln("Setup RPC server OK.\n");

	while(1)
	{
		Sleep(10);
	}

	return 0;
}
