
//#include <dir.h>

#include "pansi.h"    // header file generated by MIDL compiler
#include "panserver2.h"

//==========================================================================
// 数据采集线程
//==========================================================================
char *WINAPI GetIniFileName()
{
	static char inifile[256];
	_getcwd(inifile, 256);
	strcat(inifile, "\\Dynas.ini");
	return inifile;
}

char *WINAPI GetSubString(char *profstr, int fieldno)
{
	static char s_str[256];

	char str[257];
	char *p, *p1; //, *p2;
	int n;

	if (fieldno == 0 || strlen(profstr) == 0)
	{
		strncpy(s_str, profstr, 256);
		return s_str;
	}

	s_str[0] = 0;
	strncpy(str, profstr, 256);
	strcat(str, ",");

	p = str;
	while (*p == ' ' || *p == '\t')
		p++;

	n = 1;
	while (p1 = strstr(p, ","))
	{
		*p1 = 0;
		//p2 = p1 - 1;
		//// 去掉后置空格
		//while (*p2 == ' ' || *p2 == '\t')
		//	p2--;
		//p2++;
		//*p2 = 0;
		if (n == fieldno)
		{
			strcpy(s_str, p);
			break;
		}
		n++;

		p = p1 + 1;
		// 去掉前置空格
		while (*p == ' ' || *p == '\t')
			p++;
	}
	return s_str;
}


int WINAPI FrontEndSetup()
{
	int npoint;
	int size;
	int i, j;
	char profstr[256];
	char keystr[256];
	char *p;
	int nSOE, nAlarm, nInd;

	WSADATA wsaData;

	// System

	System.nYX = GetPrivateProfileInt("system", "nYX", 512, GetIniFileName());
	System.nYC = GetPrivateProfileInt("system", "nYC", 256, GetIniFileName());
	System.nYK = GetPrivateProfileInt("system", "nYD", 64, GetIniFileName());
	System.nYT = GetPrivateProfileInt("system", "nYT", 20, GetIniFileName());


	// YX
	//
	ppModYX = (Modbus_YX *)malloc(System.nYX * sizeof(Modbus_YX));
	for (i = 0; i < System.nYX; i++)
	{
		char defname[41];
		char keyname[41];
		sprintf(defname, "YX_%04d", i);
		sprintf(keyname, "YX_%d", i);
		GetPrivateProfileString("point", keyname, "", keystr, 256, GetIniFileName());
		p = GetSubString(keystr, 1);
		ppModYX[i].station = atoi(p);

		p = GetSubString(keystr, 2);
		ppModYX[i].point = atoi(p);

		p = GetSubString(keystr, 3);
		ppModYX[i].addr = strtol(p, NULL, 16);
	}

	// YC
	//
	ppModYC = (Modbus_YC *)malloc(System.nYC * sizeof(Modbus_YC));
	for (i = 0; i < System.nYC; i++)
	{
		char defname[41];
		char keyname[41];
		sprintf(defname, "YC_%04d", i);
		sprintf(keyname, "YC_%d", i);
		GetPrivateProfileString("point", keyname, "", keystr, 256, GetIniFileName());
		p = GetSubString(keystr, 1);
		ppModYC[i].station = atoi(p);

		p = GetSubString(keystr, 2);
		ppModYC[i].point = atoi(p);

		p = GetSubString(keystr, 3);
		ppModYC[i].k = atoi(p);

		p = GetSubString(keystr, 4);
		ppModYC[i].addr = strtol(p, NULL, 16);
	}

	//YK
	//
	ppModYK = (Modbus_YK *)malloc(System.nYK * sizeof(Modbus_YK));
	for (i = 0; i < System.nYK; i++)
	{
		char defname[41];
		char keyname[41];
		sprintf(defname, "YK_%04d", i);
		sprintf(keyname, "YK_%d", i);
		GetPrivateProfileString("point", keyname, "", keystr, 256, GetIniFileName());
		p = GetSubString(keystr, 1);
		ppModYK[i].station = atoi(p);

		p = GetSubString(keystr, 2);
		ppModYK[i].point = atoi(p);

		p = GetSubString(keystr, 3);
		ppModYK[i].addr = strtol(p, NULL, 16);
	}

	//YT
	//
	ppModYT = (Modbus_YT *)malloc(System.nYK * sizeof(Modbus_YT));
	for (i = 0; i < System.nYT; i++)
	{
		char defname[41];
		char keyname[41];
		sprintf(defname, "YT_%04d", i);
		sprintf(keyname, "YT_%d", i);
		GetPrivateProfileString("point", keyname, "", keystr, 256, GetIniFileName());
		p = GetSubString(keystr, 1);
		ppModYT[i].station = atoi(p);

		p = GetSubString(keystr, 2);
		ppModYT[i].point = atoi(p);

		p = GetSubString(keystr, 3);
		ppModYT[i].addr = strtol(p, NULL, 16);
	}
}





void WINAPI FrontEndCleanup()
{
	if (ppModYT)
		free(ppModYT);
	if (ppModYT)
		free(ppModYT);
	if (ppModYT)
		free(ppModYT);
	if (ppModYT)
		free(ppModYT);
	WSACleanup();
}