#include <windows.h>
#include <stdlib.h>
#include <stdio.h>
#include <dos.h>
#include <direct.h>
#include <time.h>
#include <sys\timeb.h>
//#include <dir.h>

#include "pansi.h"    // header file generated by MIDL compiler
#include "panserver2.h"

/***************************************************************************/
/* try_mutex and mutex-var functions */

int WINAPI try_mutex(mutex_handle mutex)
{
#ifdef _WIN32
	if (WaitForSingleObject(mutex, 0) == WAIT_TIMEOUT)
		return 1;
	ReleaseSemaphore(mutex, 1, NULL);
	return 0;
#else	/*UNIX*/
	if (sem_trywait(&mutex) != 0)
		return 1;
	sem_post(&mutex);
	return 0;
#endif
}

int WINAPI _init_var(int *var, mutex_handle *pmutex, int v0)
#ifdef _WIN32
{
	create_mutex(*pmutex); *var = v0; return *pmutex ? 1 : 0;
}
#else
{ *var = v0; return create_mutex(*pmutex) == 0 ? 1 : 0; }
#endif

void WINAPI _close_var(mutex_handle mutex)
{
	close_mutex(mutex);
}
int WINAPI _get_var(int *var, mutex_handle hm)
{
	int v; waitfor_mutex(hm); v = *var; release_mutex(hm); return v;
}
void WINAPI _set_var(int *var, mutex_handle hm, int v)
{
	waitfor_mutex(hm); *var = v; release_mutex(hm);
}
void WINAPI _inc_var(int *var, mutex_handle hm)
{
	waitfor_mutex(hm); (*var)++; release_mutex(hm);
}
void WINAPI _dec_var(int *var, mutex_handle hm)
{
	waitfor_mutex(hm); (*var)--; release_mutex(hm);
}

///////////////////////////////////////////////////////////////////////////////

void WINAPI DebugPrintf(char *fmt, ...)
{
	char str[1024];
	va_list argptr;

	va_start (argptr, fmt);
	vsprintf (str, fmt, argptr);
	va_end (argptr);

	printf(str);
}

void WINAPI DebugPrintln(char *str)
{
	printf(str);
	printf("\n");
}

///////////////////////////////////////////////////////////////////////////////

char *WINAPI GetIniFileName()
{
	static char inifile[256];
	_getcwd(inifile, 256);
	strcat(inifile, "\\Dynas.ini");
	return inifile;
}

char *WINAPI GetSubString(char *profstr, int fieldno)
{
	static char s_str[256];

	char str[257];
	char *p, *p1; //, *p2;
	int n;

	if (fieldno == 0 || strlen(profstr) == 0)
	{
		strncpy(s_str, profstr, 256);
		return s_str;
	}

	s_str[0] = 0;
	strncpy(str, profstr, 256);
	strcat(str, ",");

	p = str;
	while (*p == ' ' || *p == '\t')
		p++;

	n = 1;
	while (p1 = strstr(p, ","))
	{
		*p1 = 0;
		//p2 = p1 - 1;
		//// 去掉后置空格
		//while (*p2 == ' ' || *p2 == '\t')
		//	p2--;
		//p2++;
		//*p2 = 0;
		if (n == fieldno)
		{
			strcpy(s_str, p);
			break;
		}
		n++;

		p = p1 + 1;
		// 去掉前置空格
		while (*p == ' ' || *p == '\t')
			p++;
	}
	return s_str;
}

long WINAPI MergeVarID(int dtype, int station, int point, int func)
{
	return MAKELONG((point & 0x0fff) | ((func << 12) & 0xf000),
		(station & 0x0fff) | ((dtype << 12) & 0xf000));
}

void WINAPI SplitVarID(long varID, int *dtype, int *station,
	int *point, int *func)
{
	WORD lw, hw;
	lw = LOWORD(varID);
	hw = HIWORD(varID);

	if (dtype)	*dtype = (hw & 0xf000) >> 12;
	if (station)	*station = hw & 0x0fff;
	if (point) 	*point = lw & 0xfff;
	if (func)		*func = (lw & 0xf000) >> 12;
}

int WINAPI GetVarType(long varID)
{
	int vtype;
	SplitVarID(varID, &vtype, 0, 0, 0);

	return vtype;
}

int WINAPI GetVarExtType(long varID)
{
	int func;
	SplitVarID(varID, 0, 0, 0, &func);

	return func;
}

int WINAPI GetVarStation(long varID)
{
	int station;
	SplitVarID(varID, 0, &station, 0, 0);

	return station;
}

int WINAPI GetVarPoint(long varID)
{
	int point;
	SplitVarID(varID, 0, 0, &point, 0);

	return point;
}

#ifdef _MSC_VER

void gettime(struct time *timep)
{
	struct tm *pt;
    time_t long_time;
 	struct _timeb timebuffer;

	time( &long_time );          
    pt = localtime(&long_time); 
	_ftime(&timebuffer);

    timep->ti_hour = pt->tm_hour;
    timep->ti_min = pt->tm_min;
    timep->ti_sec = pt->tm_sec;

    timep->ti_hund = timebuffer.millitm / 10;
}

void getdate(struct date *datep)
{
	struct tm *pt;
    time_t long_time;

	time( &long_time );          
    pt = localtime(&long_time); 

    datep->da_year = pt->tm_year;
    datep->da_day = pt->tm_mday;
    datep->da_mon = pt->tm_mon;
}

#endif

