// Dynaserver.cpp

#include <windows.h>
#include <process.h>
#include <stdio.h>

#include "pansi.h"    // header file generated by MIDL compiler
#include "panserver.h"
#include "panserver2.h"


int main(int atgc, char *argv[])
{
	//¹Ø±Õ°´Å¥±ä»Ò
	DeleteMenu(GetSystemMenu(GetConsoleWindow(), FALSE), SC_CLOSE, MF_BYCOMMAND);
	DrawMenuBar(GetConsoleWindow());
	if (FrontEndSetup() < 0)
	{
		DebugPrintln("FrontEnd Setup Failure.");
		exit(-1);
	}
	DebugPrintln("FrontEnd Setup OK.");

	int i;
	HANDLE hThread[10] = { 0 };
	unsigned threadid[10] = { 0 };

	//DWORD id;
	//for (i = 0; i < System.nstation; i++)
	//{
	//	int station = i;
	//	CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)FrontEndRoutine, (LPVOID)station, 0, &id);
	//}
	//CreateThread (NULL, 0, (LPTHREAD_START_ROUTINE)RPCSetup, 0, 0, &id);
	for (i = 0; i < System.nstation; i++)
	{
		Astation value;
		value.station = i;
		hThread[i] = (HANDLE)_beginthreadex(NULL, 0, FrontEndRoutine, &value, 0, &threadid[i]);
		Sleep(100);
	}
	hThread[System.nstation] = (HANDLE)_beginthreadex(NULL, 0, RPCSetup, 0, 0, &threadid[System.nstation]);
	DebugPrintln("Setup RPC server OK.\n");

	while(1)
	{
		Sleep(500);
	}
	CloseHandle(hThread);
	FrontEndCleanup();
	RPCCleanup(0);
	return 0;
}
