
#include "pansi.h"    // header file generated by MIDL compiler
#include "panserver2.h"

#ifdef __cplusplus
extern "C"{
#endif 

// Global Vars
EN_ssystem System;
EN_sstation *pStation = NULL;
EN_yyx **ppYX  = NULL;
EN_yyc **ppYC  = NULL;
EN_yyd **ppYD  = NULL;
EN_yyt **ppYT  = NULL;
EN_SOE **ppSOE = NULL;
EN_Alarm **ppAlarm= NULL;
EN_Ind **ppInd = NULL;
char rulestr[256];

DEF_VAR(Flag_FER)
DEF_VAR(Count_FER)
DEF_VAR(VarID_OPER)
float Var_OPER;
mutex_handle Mutex_RT = NULL;
mutex_handle file_RT = NULL;

ENEVENT pEventBuf[MAXNUM_EVENT];
mutex_handle Mutex_EVENT = NULL;
int Num_Event = 0;



#ifdef __cplusplus
}
#endif