#include <stdio.h>

#include "pansi.h"    // header file generated by MIDL compiler
#include "Dynaclient.h"

extern BOOL g_fNetConnected;
LRESULT WINAPI NetSetupThread (LPVOID lp);

int main()
{
	DWORD id;
	CreateThread (NULL, 0, (LPTHREAD_START_ROUTINE)NetSetupThread, 0, 0, &id);

	long yx_pids[2048];
	long yc_pids[2048];
	long yk_varid;
	long yt_varid;
	PS_rt_yx __RPC_FAR yx_data[2048];
	PS_rt_yc __RPC_FAR yc_data[2048];
	BOOL connect = 0;
	while (1)
    {
        __try
        {
			for (int i = 0; i < 30; i++)
			{
				yx_pids[i] = MergeVarID(VARTYPE_YX, 1, i + 1, 0);  //Ò£ÐÅ
			}
			RPC_GetRealtimeYXData(yx_pids, yx_data, 30);
			for (int k = 0; k < 30; k++)
			{
				//printf("%d:%d\n", k + 1, yx_data[k].value);
			}
			for (int j = 0; j < 20; j++)
			{
				yc_pids[j] = MergeVarID(VARTYPE_YC, 1, j + 1, 0);  //Ò£²â
			}
			RPC_GetRealtimeYCData(yc_pids, yc_data, 20);
			for (int m = 0; m < 20; m++)
			{
				//printf("%d:%f\n", m + 1, yc_data[m].value);
			}
			long yk_varid = MergeVarID(VARTYPE_YX, 1, 300, 0);
			RPC_YKRequest(yk_varid, 1, "nothing");
			RPC_YKExecute(yk_varid, 1, "nothing");             //Ò£¿Ø
			long yt_varid = MergeVarID(VARTYPE_YC, 1, 105, 0);
			RPC_YKRequest(yt_varid, 123.32, "nothing");
			RPC_YKExecute(yt_varid, 123.32, "nothing");        //Ò£µ÷
       	}
        __except(1)
        {
			printf("fail to receive datas!\n");
        }

        Sleep (200);
    }

	return 0;
}